blank_issues_enabled: false
contact_links:
  - name: Issues in Problem Solving with Algorithms and Data Structures using C++
    url:  https://github.com/pearcej/cppds/issues
    about: Please post bug reports and recommendations for improvement here.
